// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-northeast-1:73fbf8a1-afc8-419d-8ff3-b6b9b82f0094',
    'aws_cognito_region': 'ap-northeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'mobileauth-hosting-mobilehub-997107525',
    'aws_content_delivery_bucket_region': 'ap-northeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd54qhwmh1eg0z.cloudfront.net',
    'aws_mobile_analytics_app_id': 'f8cc51fb469d4105a9b880f3d4c085be',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a68836db-7898-4e48-9728-bd818d334deb',
    'aws_project_name': 'mobile-auth',
    'aws_project_region': 'ap-northeast-1',
    'aws_resource_name_prefix': 'mobileauth-mobilehub-997107525',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-northeast-1_e4crjbFfU',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '7c8tkl9s200vib12uru0vb7qun',
}

export default awsmobile;
